import {
  FieldDefinition,
  FieldInputType,
  FieldWidth,
} from "@/components/ui/dialog-create";

export const clientFields: FieldDefinition[] = [
  {
    name: "firstName",
    label: "Imię",
    section: "Dane osobowe",
    width: FieldWidth.Half,
    type: FieldInputType.Text,
    placeholder: "Wprowadź imię",
  },
  {
    name: "lastName",
    label: "Nazwisko",
    section: "Dane osobowe",
    width: FieldWidth.Half,
    type: FieldInputType.Text,
    placeholder: "Wprowadź nazwisko",
  },
  {
    name: "email",
    label: "E-mail",
    section: "Dane osobowe",
    type: FieldInputType.Email,
    width: FieldWidth.Half,
    placeholder: "Wprowadź e-mail",
  },
  {
    name: "phoneNumber",
    label: "Numer telefonu",
    section: "Dane osobowe",
    type: FieldInputType.Tel,
    width: FieldWidth.Half,
    placeholder: "Wprowadź numer telefonu",
  },
  {
    name: "dateOfBirth",
    label: "Data urodzenia",
    section: "Dane osobowe",
    type: FieldInputType.Date,
  },
  {
    name: "street",
    label: "Ulica",
    section: "Adres",
    type: FieldInputType.Text,
    placeholder: "Wprowadź ulicę",
  },
  {
    name: "city",
    label: "Miasto",
    section: "Adres",
    width: FieldWidth.Third,
    type: FieldInputType.Text,
    placeholder: "Wprowadź miasto",
  },
  {
    name: "state",
    label: "Województwo",
    section: "Adres",
    width: FieldWidth.Third,
    type: FieldInputType.Text,
    placeholder: "Wprowadź województwo",
  },
  {
    name: "postalCode",
    label: "Kod pocztowy",
    section: "Adres",
    width: FieldWidth.Third,
    type: FieldInputType.Text,
    placeholder: "Wprowadź kod pocztowy",
  },
  {
    name: "country",
    label: "Kraj",
    type: FieldInputType.Select,
    section: "Adres",
    options: [
      { label: "Polska", value: "Polska" },
      { label: "Niemcy", value: "Niemcy" },
      { label: "Czechy", value: "Czechy" },
      { label: "Słowacja", value: "Słowacja" },
      { label: "Ukraina", value: "Ukraina" },
      { label: "Inne", value: "Inne" },
    ],
    placeholder: "Wybierz kraj",
  },
  {
    name: "notes",
    label: "Notatki",
    type: FieldInputType.Textarea,
    section: "Dodatkowe informacje",
    placeholder: "Wprowadź dodatkowe informacje o kliencie",
  },
];
